custom_movie.award_winning_movie.*:
  type: config_entity
  label: Award winning Movie
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    year:
      type: date
