<?php

use Drupal\Core\Entity\EntityInterface;

/**
* Implements hook_entity_view().
*/
/**
 * Method custom_movie_entity_view
 *
 * @param array $build [explicite description]
 * @param EntityInterface $entity [explicite description]
 * @param $view_mode $view_mode [explicite description]
 * @param $langcode $langcode [explicite description]
 *
 * @return void
 */
// function custom_movie_entity_view(array &$build, EntityInterface $entity, $view_mode, $langcode)
// {
//   if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'movie') {
//     /** @var \Drupal\custom_movie\EventSubscriber\MovieComparison $movie_comparison */
//     $movie_comparison = \Drupal::service('movie_price_comparision_event');
//     $movie_comparison->getComparison($build, $entity);
//   }
// }
