<?php

/**
 * @file
 * Implement the needed hooks.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Method custom_movie_entity_view to view the message.
 *
 * @param array $build
 *   [Explicite description].
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   [Explicite description].
 */
function custom_movie_entity_view(array &$build, EntityInterface $entity) {

  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'movie') {

    // Getting the budget from confg form.
    $config = \Drupal::config('custom_movie.settings');
    $budget = $config->get('price');

    // Getting the movie price from node.
    $movie_price = $entity->get('field_movie_price')->value;

    if ($budget > $movie_price) {
      $message = 'The movie is under budget';
    }
    elseif ($budget < $movie_price) {
      $message = 'The movie is over budget';
    }
    else {
      $message = 'The movie is within budget';
    }

    $build['status'] = [
      '#markup' => $message,
      '#cache' => [
        'tags' => ['BUDGET_UPDATE'],
      ],
    ];
  }
}
