field.value.color_picker_rgb_color_picker:
  type: mapping
  label: Default value
  mapping:
    r:
      type: string
      label: Red
    g:
      type: string
      label: Green
    b:
      type: string
      label: Blue
